### ISSUE TITLE
No private messages could be sent in shiori!

### ISSUE THREAD

**Issue by r0neko** [osu-katakuna/shiori#4]

**Comment by r0neko** [comment]
@lenforiee I give you this task! DO IT! :))

**Comment by lenforiee** [comment]
I will don't worry I was just busy yesterday lmao

**Comment by r0neko** [comment]
fixed starting from commit 23c131c416d2a192a87ab36d1e5ff76d6356bc70 - 06cb994dbd3183d0ad7e28a731e402c8dbda4a38
